In [5]:
#iniciar o notebook com as importações necessárias
#se aparecer erro aqui, significa que a biblioteca não está instalada, e você deve instalar usando pip install nome_da_biblioteca

import pandas as pd #biblioteca para manipulação de dados
import re #biblioteca para expressões regulares
from datetime import datetime #biblioteca para manipulação de datas

# confirmarque as bibliotecas foram importadas corretamente
print("pandas versão:", pd.__version__)
print("re versão:", re.__version__)

pandas versão: 3.0.2
re versão: 2.2.1

In [6]:
#pd.read_csv() é a função para ler arquivos CSV e criar um DataFrame
#CAMINHO DO ARQUIVO: é o caminho onde o arquivo está localizado no seu computador
#basta informar o nome do arquivo se ele estiver na mesma pasta do notebook, ou o caminho completo se estiver em outra pasta
#exemplo: df = pd.read_csv("dados.csv") ou df = pd.read_csv

CAMINHO = r"C:\Users\Usuário\Downloads\SCTEC\turma-visualizacao-de-dados\aula_05_05\turma-visualizacao-de-dados\alunos\lourenco_lemos\semana_04\base_rh.csv"

df = pd.read_csv(
    CAMINHO,
    sep=";", #separador de campos, no caso é ";"
    encoding="cp1252", #codificação do arquivo, no caso é "cp1252" para arquivos em português
    decimal=",", #separador decimal, no caso é "," para arquivos em português
    thousands=".", #separador de milhares, no caso é "." para arquivos em português
    )

print("DataFrame criado com sucesso!")
print(f' total de linhas: {df.shape[0]}')
print(f' total de colunas: {df.shape[1]}')

DataFrame criado com sucesso!
 total de linhas: 1000
 total de colunas: 10

In [ ]:
#df.head() mostra as primeiras 5 linhas do DataFrame, útil para verificar se os dados foram carregados corretamente
#use para ter uma visão rápida dos dados e verificar se as colunas estão corretas e os dados no formato esperado
df.head()

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,16/06/2019,M,50,Casado,Inativo
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,29/03/2019,F,62,Casado,Inativo

In [9]:
#df.tail() mostra as últimas 5 linhas do DataFrame, útil para verificar se os dados foram carregados corretamente e se não há linhas em branco no final do arquivo
#use para ter uma visão rápida dos dados e verificar se as colunas estão corretas e os dados no formato esperado, especialmente se o arquivo tiver muitas linhas
df.tail(10) #mostra as últimas 10 linhas do DataFrame

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
990,991,Sr. Vicente Silveira,Produção,Gerente,8026.70,11/07/2021,F,55,Viúvo,Inativo
991,992,Emanuel da Cruz,Logística,Gerente,12572.11,30/01/2024,M,33,Viúvo,Ativo
992,993,Enrico Monteiro,RH,Coordenador,14677.33,26/12/2017,M,52,Divorciado,Inativo
993,994,Ana Lívia Cardoso,RH,Coordenador,14912.48,22/10/2015,M,27,Solteiro,Inativo
994,995,Fernando Monteiro,RH,Assistente,10983.02,09/01/2023,F,42,Viúvo,Ativo
995,996,Matheus Aragão,Financeiro,Analista,11389.03,06/05/2022,F,26,Viúvo,Ativo
996,997,Ryan Martins,Financeiro,Analista,14060.42,05/06/2023,F,37,Viúvo,Ativo
997,998,Isabelly Ferreira,TI,Gerente,2348.73,29/12/2023,F,58,Solteiro,Inativo
998,999,Thales Farias,Produção,Analista,9430.62,25/12/2019,M,41,Solteiro,Ativo
999,1000,Sra. Maysa Costela,Produção,Técnico,12549.72,14/11/2022,M,46,Viúvo,Inativo

In [10]:
#df.columns mostra os nomes das colunas do DataFrame, útil para verificar se as colunas foram carregadas corretamente e para saber quais colunas estão disponíveis para análise
#use para ter uma visão rápida dos nomes das colunas e verificar se estão corretos, especialmente se o arquivo tiver muitas colunas
#to.list() converte o índice das colunas em uma lista, facilitando a visualização e manipulação dos nomes das colunas
#df.columns.to_list()

print("Colunas do DataFrame:")
print(df.columns.to_list())

Colunas do DataFrame:
['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

In [11]:
#df.info() mostra informações sobre o DataFrame, como o número de linhas, colunas, tipos de dados e memória utilizada
#use para ter uma visão geral do DataFrame e verificar se os tipos de dados estão corretos, se há colunas com muitos valores nulos e para ter uma ideia da estrutura dos dados
#comando mais importante para iniciar a análise dos dados, pois ajuda a identificar possíveis problemas com os dados, como colunas com muitos valores nulos ou tipos de dados incorretos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   str
 2   Departamento    1000 non-null   str
 3   Cargo           1000 non-null   str
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   str
 6   Genero          1000 non-null   str
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   str
 9   Status          1000 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 78.3 KB

In [12]:
#df.isnull() mostra um DataFrame booleano indicando onde há valores nulos (True) e onde não há (False)
#use para identificar onde estão os valores nulos no DataFrame, o que é importante para decidir como lidar com eles (excluir, preencher, etc.)
df.isnull()

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False

In [15]:
#.sum() soma os valores booleanos, ou seja, conta quantos valores nulos há em cada coluna
#use para ter uma visão rápida de quantos valores nulos há em cada coluna, o que é importante para decidir como lidar com eles (excluir, preencher, etc.)
print("Quantidade de valores nulos por coluna:")
print(df.isnull().sum())

print()

#percentual de valores nulos em cada coluna
#use para ter uma visão rápida do percentual de valores nulos em cada coluna, o que é importante para decidir como lidar com eles (excluir, preencher, etc.)
print("Percentual de valores nulos por coluna:")
print((df.isnull().sum() / len(df)) * 100)

Quantidade de valores nulos por coluna:
ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

Percentual de valores nulos por coluna:
ID_Funcionario    0.0
Nome              0.0
Departamento      0.0
Cargo             0.0
Salario           0.0
Data_Admissao     0.0
Genero            0.0
Idade             0.0
Estado_Civil      0.0
Status            0.0
dtype: float64

In [16]:
#df.describe() mostra estatísticas descritivas das colunas numéricas do DataFrame, como média, desvio padrão, valores mínimos e máximos, etc.
#use para ter uma visão geral das colunas numéricas do DataFrame e identificar possíveis outliers, tendências e para ter uma ideia da distribuição dos dados
df.describe().round(2) #arredonda os valores para 2 casas decimais

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

In [17]:
#df.nunique() mostra o número de valores únicos em cada coluna, útil para identificar colunas categóricas e para ter uma ideia da diversidade dos dados
#use para identificar colunas categóricas (que geralmente têm poucos valores únicos) e para ter uma ideia da diversidade dos dados em cada coluna
print("Número de valores únicos por coluna:")
print(df.nunique())

Número de valores únicos por coluna:
ID_Funcionario    1000
Nome               976
Departamento         6
Cargo                5
Salario           1000
Data_Admissao      878
Genero               2
Idade               48
Estado_Civil         4
Status               2
dtype: int64