In [1]:
import pandas as pd
import re # expressões regulates (para limpar texto)
from datetime import datetime # bib para trabalhar com datas

# testando as importações
print('Pandas versão:', pd.__version__)
print('Bibliotecas importadas')

Pandas versão: 2.3.3
Bibliotecas importadas

In [4]:
# importando o arquivo CSV - locao do arquivo CSV
CAMINHO = R"C:\turma-visualizacao-de-dados\alunos\sergio_leite\semana_04\base_rh.csv"

# pd.read_csv vai ler e add os dados de leitura a variavel df que será usada para acessar o arquivo e gerar dados

df = pd.read_csv(
    CAMINHO,
    sep=';', # padrão de ; para separar colunas e não virgula
    encoding='cp1252', # encoding do windows para leitura de acentos
    decimal=',' # add padrão de virgula para separar decimais
)

print('Dados carregados corretamente')
print(f'Total de linhas: {df.shape[0]}') # df.shape[0] se refere ao numero de linhas
print(f'Total de colunas: {df.shape[1]}') # df.shape[1] se refere ao numero de colunas

Dados carregados corretamente
Total de linhas: 1000
Total de colunas: 10

In [ ]:
print('Seguem as 5 primeiras linhas') # ajuda a verificar se as linhas iniciais foram lidas corretamente
print(df.head(5)) # chama a var df e solicita os 5 primeiras linhas do inicio

print('Seguem as últimas 5 linhas') # ajuda a verificar se as linhas finais foram lidas corretamente
print(df.tail(5)) # solicita ao df as últimas 5 linhas

Seguem as 5 primeiras linhas
   ID_Funcionario                 Nome Departamento        Cargo   Salario  \
0               1          Julia Nunes    Logística  Coordenador   9088.34
1               2   Sr. Gustavo Duarte           TI      Gerente   8155.98
2               3  Srta. Mariana Cunha           RH  Coordenador  14027.93
3               4   Ana Sophia da Cruz     Produção      Técnico   6647.97
4               5    Dr. Nicolas Pinto     Produção      Gerente   8730.19

  Data_Admissao Genero  Idade Estado_Civil   Status
0    13/08/2024      F     43     Solteiro  Inativo
1    29/04/2017      F     59     Solteiro  Inativo
2    11/12/2024      F     27   Divorciado    Ativo
3    16/06/2019      M     50       Casado  Inativo
4    29/03/2019      F     62       Casado  Inativo
Seguem as últimas 5 linhas
     ID_Funcionario                Nome Departamento     Cargo   Salario  \
995             996      Matheus Aragão   Financeiro  Analista  11389.03
996             997        Ryan Martins   Financeiro  Analista  14060.42
997             998   Isabelly Ferreira           TI   Gerente   2348.73
998             999       Thales Farias     Produção  Analista   9430.62
999            1000  Sra. Maysa Costela     Produção   Técnico  12549.72

    Data_Admissao Genero  Idade Estado_Civil   Status
995    06/05/2022      F     26        Viúvo    Ativo
996    05/06/2023      F     37        Viúvo    Ativo
997    29/12/2023      F     58     Solteiro  Inativo
998    25/12/2019      M     41     Solteiro    Ativo
999    14/11/2022      M     46        Viúvo  Inativo

In [14]:
# df.columns mostra as colunas do dataset
# tolist transforma o index de colunas em uma lista e ajuda a acessar para fazer modificações em nomes, por exemplo.

print(df.columns.tolist()) # mostra as colunas do dataset

['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

In [19]:
matriz_dados = df.values.tolist() # cria a matriz de dados sendo uma lista python com todos os dados do dataframe

print(matriz_dados[9])

[10, 'Davi Lucca Teixeira', 'Produção', 'Gerente', 13512.53, '29/06/2020', 'M', 35, 'Viúvo', 'Ativo']

In [ ]:
# df.info() faz o resumo completo do DF em um comando
# mostra o nome de cada coluna, quantidade de valores nao nulos, tipos de dados (dtype), uso de memoria 
# é um comando muito útil para um primeiro diagnóstico da base de dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   object
 2   Departamento    1000 non-null   object
 3   Cargo           1000 non-null   object
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   object
 6   Genero          1000 non-null   object
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   object
 9   Status          1000 non-null   object
dtypes: float64(1), int64(2), object(7)
memory usage: 78.3+ KB

In [35]:
# para saber a quantidade de dados nulos no DF
# o df.isnull cria uma tabela true / false onde ons true são os nulos
# .sum() vai somar os true de cada coluna (true 1 e false 0)

print('Quantidade de dados nulos por coluna no data frame')
print(df.isnull().sum())
print() # pular uma linha

# calculando o percentual de nulos
# len(df) vai pegar a quandidade de linhas do DF
# calcular o percentual de nulos é muito útil em grandes bases para entender a proporção de nulos

print('O percentual de nulos no DF é: ')
print((df.isnull().sum() / len(df) * 100).round(2))

Quantidade de dados nulos por coluna no data frame
ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

O percentual de nulos no DF é:
ID_Funcionario    0.0
Nome              0.0
Departamento      0.0
Cargo             0.0
Salario           0.0
Data_Admissao     0.0
Genero            0.0
Idade             0.0
Estado_Civil      0.0
Status            0.0
dtype: float64

In [ ]:
# O describe() é muito usado para ver a estatistica descritiva das colunas numéricas 
# ajuda a confirmar que dados estão no formato esperado, sem valores absurdos e sem erros de leituras ou outros erros.
# count - quantos valores não nulos existem
# mean - média
# std - Desvio padrão - o quanto os valores variam em torno da média
# min - Menor valor
# 25% - 25% dos registros estão abaixo desse valor
# 50% - mediana. 50% dos registros abaixo de 50%
# 75% - 75% dos registros estão abaixo desse valor
# max - Maior valor

df.describe().round(2) # o round(2) limita o valor a 2 casas decimais

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

In [ ]:
# Explorando colunas
# # df.nunique() vai mostrar valores únicos por coluna
# Ajuda a identificar quais são categorias (poucas opções) e quais sao identificadores (muitas opções diferentes)
# nunique() - conta quantos valores diferentes existem 
# value_counts() mostra a distribuição - quantas vezes cada valor aparece
print('Valores únicos por coluna')
print(df.nunique())

Valores únicos por coluna
ID_Funcionario    1000
Nome               976
Departamento         6
Cargo                5
Salario           1000
Data_Admissao      878
Genero               2
Idade               48
Estado_Civil         4
Status               2
dtype: int64

In [53]:
# Explorando colunas
# df['Salario'].value_counts() #  conta quantas vezes cada valor apaece na coluna escolhida

for col in ['Departamento', 'Cargo', 'Genero', 'Status', 'Estado_Civil']:
    print(f'\n --- {col} ---')
    print(df[col].value_counts())

 --- Departamento ---
Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: count, dtype: int64

 --- Cargo ---
Cargo
Coordenador    225
Gerente        221
Assistente     199
Analista       178
Técnico        177
Name: count, dtype: int64

 --- Genero ---
Genero
F    510
M    490
Name: count, dtype: int64

 --- Status ---
Status
Ativo      515
Inativo    485
Name: count, dtype: int64

 --- Estado_Civil ---
Estado_Civil
Solteiro      265
Viúvo         261
Divorciado    240
Casado        234
Name: count, dtype: int64

In [ ]:
# Selecionando colunas e filtrando linhas
# df['Nome'] - seleciona a coluna
# df['Nome', 'Salario'] - Seleciona váriadas colunas
# df[df['Status'] == 'Ativo'] - Filtra de linhas

df['Departamento'].head(3) # lista os 3 primeiros departamentos
df['Departamento'].value_counts() # conta quantas vezes o valor aparece repetido na coluna

Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: count, dtype: int64

In [ ]:
# Selecionando multiplas colunas

df[['Nome', 'Cargo', 'Departamento']].value_counts()

df[['Nome', 'Cargo', 'Departamento']].head(10)

                   Nome        Cargo Departamento
0           Julia Nunes  Coordenador    Logística
1    Sr. Gustavo Duarte      Gerente           TI
2   Srta. Mariana Cunha  Coordenador           RH
3    Ana Sophia da Cruz      Técnico     Produção
4     Dr. Nicolas Pinto      Gerente     Produção
5         Marcela Costa     Analista           RH
6  João Miguel da Costa      Técnico     Produção
7     Gabrielly Cardoso     Analista           RH
8           Raul da Paz  Coordenador    Logística
9   Davi Lucca Teixeira      Gerente     Produção

In [66]:
# Filtro simples: Seleciona somente as linhas onde o status == 'Ativo'
# df['Status'] == 'Ativo' - cria uma serie true / false
# df[True / False] = mantém so as linhas true

ativos = df[df['Status'] == 'Ativo']
print(f'Total de funcionários: {len(df)}')
print(f'Funcionários ativos: {len(ativos)}')
print(f'Funcionários inativos: {len(df) - len(ativos)}')

Total de funcionários: 1000
Funcionários ativos: 515
Funcionários inativos: 485